package models

// Generated by https://quicktype.io

type CommonResponse struct {
	Errors []CommonError `json:"errors"`
	Status Status        `json:"status"`
}

type CommonError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}
