package models

// Generated by https://quicktype.io

type SetPriceRequest struct {
	Offers []Offer `json:"offers"`
}

type Offer struct {
	Feed   FeedObj `json:"feed"`
	ID     string  `json:"id"`
	Delete bool    `json:"delete"`
	Price  Price   `json:"price"`
}

type FeedObj struct {
	ID int64 `json:"id"`
}

type Price struct {
	CurrencyID   string  `json:"currencyId"`
	Value        float64 `json:"value"`
	DiscountBase float64 `json:"discountBase,omitempty"`
}

type SetPriceResponse struct {
	Status Status `json:"status"`
}

// Generated by https://quicktype.io

type GetPricesResponse struct {
	Errors CommonErrors `json:"errors"`
	Result Result       `json:"result"`
	Status Status       `json:"status"`
}

type Result struct {
	Offers []GetPriceOfferModel `json:"offers"`
	Total  int64                `json:"total"`
}

type GetPriceOfferModel struct {
	Feed      Feed   `json:"feed"`
	ID        string `json:"id"`
	Price     Price  `json:"price"`
	UpdatedAt string `json:"updatedAt"`
}
