package models

// Generated by https://quicktype.io

type RefreshResponse struct {
	Errors []RefreshError `json:"errors"`
	Status Status         `json:"status"`
}

type RefreshError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}
